"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.index import download_file
from insta485.views.index import handle_comments
from insta485.views.index import like_unlike
from insta485.views.accounts import authenticate
from insta485.views.accounts import logout
from insta485.views.accounts import edit
from insta485.views.accounts import delete
from insta485.views.accounts import create
from insta485.views.accounts import download_prof_edit
from insta485.views.accounts import handle_accounts
from insta485.views.explore import explore
from insta485.views.explore import download_pic
from insta485.views.users import user1
from insta485.views.users import handle_uploads
from insta485.views.users import download_preview
from insta485.views.posts import post
from insta485.views.follow import followers1
from insta485.views.follow import following
from insta485.views.explore import follow_button
from insta485.views.users import get_following
